// source: bottle/inventory/v1/movement.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_inventory_v1_location_pb = require('../../../bottle/inventory/v1/location_pb.js');
goog.object.extend(proto, bottle_inventory_v1_location_pb);
var bottle_inventory_v1_part_pb = require('../../../bottle/inventory/v1/part_pb.js');
goog.object.extend(proto, bottle_inventory_v1_part_pb);
goog.exportSymbol('proto.bottle.inventory.v1.Movement', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.Movement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.inventory.v1.Movement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.Movement.displayName = 'proto.bottle.inventory.v1.Movement';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.Movement.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.Movement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.Movement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.Movement.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    part: (f = msg.getPart()) && bottle_inventory_v1_part_pb.Part.toObject(includeInstance, f),
    fromLocation: (f = msg.getFromLocation()) && bottle_inventory_v1_location_pb.Location.toObject(includeInstance, f),
    toLocation: (f = msg.getToLocation()) && bottle_inventory_v1_location_pb.Location.toObject(includeInstance, f),
    insertedAt: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.Movement}
 */
proto.bottle.inventory.v1.Movement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.Movement;
  return proto.bottle.inventory.v1.Movement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.Movement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.Movement}
 */
proto.bottle.inventory.v1.Movement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new bottle_inventory_v1_part_pb.Part;
      reader.readMessage(value,bottle_inventory_v1_part_pb.Part.deserializeBinaryFromReader);
      msg.setPart(value);
      break;
    case 3:
      var value = new bottle_inventory_v1_location_pb.Location;
      reader.readMessage(value,bottle_inventory_v1_location_pb.Location.deserializeBinaryFromReader);
      msg.setFromLocation(value);
      break;
    case 4:
      var value = new bottle_inventory_v1_location_pb.Location;
      reader.readMessage(value,bottle_inventory_v1_location_pb.Location.deserializeBinaryFromReader);
      msg.setToLocation(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setInsertedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.Movement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.Movement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.Movement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.Movement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPart();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_inventory_v1_part_pb.Part.serializeBinaryToWriter
    );
  }
  f = message.getFromLocation();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      bottle_inventory_v1_location_pb.Location.serializeBinaryToWriter
    );
  }
  f = message.getToLocation();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      bottle_inventory_v1_location_pb.Location.serializeBinaryToWriter
    );
  }
  f = message.getInsertedAt();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.Movement.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.Movement} returns this
 */
proto.bottle.inventory.v1.Movement.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Part part = 2;
 * @return {?proto.bottle.inventory.v1.Part}
 */
proto.bottle.inventory.v1.Movement.prototype.getPart = function() {
  return /** @type{?proto.bottle.inventory.v1.Part} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_part_pb.Part, 2));
};


/**
 * @param {?proto.bottle.inventory.v1.Part|undefined} value
 * @return {!proto.bottle.inventory.v1.Movement} returns this
*/
proto.bottle.inventory.v1.Movement.prototype.setPart = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.Movement} returns this
 */
proto.bottle.inventory.v1.Movement.prototype.clearPart = function() {
  return this.setPart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.Movement.prototype.hasPart = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Location from_location = 3;
 * @return {?proto.bottle.inventory.v1.Location}
 */
proto.bottle.inventory.v1.Movement.prototype.getFromLocation = function() {
  return /** @type{?proto.bottle.inventory.v1.Location} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_location_pb.Location, 3));
};


/**
 * @param {?proto.bottle.inventory.v1.Location|undefined} value
 * @return {!proto.bottle.inventory.v1.Movement} returns this
*/
proto.bottle.inventory.v1.Movement.prototype.setFromLocation = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.Movement} returns this
 */
proto.bottle.inventory.v1.Movement.prototype.clearFromLocation = function() {
  return this.setFromLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.Movement.prototype.hasFromLocation = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Location to_location = 4;
 * @return {?proto.bottle.inventory.v1.Location}
 */
proto.bottle.inventory.v1.Movement.prototype.getToLocation = function() {
  return /** @type{?proto.bottle.inventory.v1.Location} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_location_pb.Location, 4));
};


/**
 * @param {?proto.bottle.inventory.v1.Location|undefined} value
 * @return {!proto.bottle.inventory.v1.Movement} returns this
*/
proto.bottle.inventory.v1.Movement.prototype.setToLocation = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.Movement} returns this
 */
proto.bottle.inventory.v1.Movement.prototype.clearToLocation = function() {
  return this.setToLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.Movement.prototype.hasToLocation = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string inserted_at = 5;
 * @return {string}
 */
proto.bottle.inventory.v1.Movement.prototype.getInsertedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.Movement} returns this
 */
proto.bottle.inventory.v1.Movement.prototype.setInsertedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.bottle.inventory.v1);
